# files
MAP_SRC = 'img/map.png'
CSV_FOLDER = 'data'
TARGET_FOLDER = 'result'
ANIMATION_NAME = 'animation.gif'

# animation
FRAME_DURATION = 1000

# map coords
WEST_COORD = 46
OST_COORD = 88
NORD_COORD = 56
SOUTH_COORD = 40

# pallette colors
H_FROM = 0
H_TO = 240
L = 0.5
S = 1

# palette
PALETTE_HEIGHT = 250
PALETTE_WIDTH = 30
PALETTE_POSITION_X = 10
PALETTE_POSITION_Y = 620
PALETTE_COLORS_COUNT = 10
PALETTE_FONT_NAME = 'arial'
PALETTE_FONT_SIZE = 19
PALETTE_FONT_COLOR_R = 100
PALETTE_FONT_COLOR_G = 100
PALETTE_FONT_COLOR_B = 100
PALETTE_TEXT_MARGIN = 3

# SPEI
SPEI_FROM = -2.33
SPEI_TO = 2.33


# drawing point
RECT_OPACITY = 80
RECT_HEIGHT = 14
RECT_WIDTH = 9

# title
TITLE_POSITION_X = 80
TITLE_POSITION_Y = 50
TITLE_FONT_NAME = 'arial'
TITLE_FONT_SIZE = 75
TITLE_FONT_COLOR_R = 255
TITLE_FONT_COLOR_G = 255
TITLE_FONT_COLOR_B = 255
TITLE_FONT_OPACITY= 120
